config/routes.rb
Rails.application.routes.draw do

  root to: 'static_pages#home'

  devise_for :users
  devise_for skip: :all
  resources :posts
  resources :comments
  resources :tags, only: [:index, :show]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post

  default_scope -> { order(created_at: :desc) }

  validates :content, presence: true, length: { maximum: 140 }
end

app/models/micropost.rb
class Micropost < ApplicationRecord
  belongs_to :user
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user

  has_many :comments

  acts_as_taggable_on :tags

  mount_uploader :picture, PictureUploader

  validates :content, presence: true, length: { maximum: 140 }
  validate  :picture_size

  default_scope -> { order(created_at: :desc) }

  private

    # Validates the size of an uploaded picture.
  def picture_size
    if picture.size > 5.megabytes
      errors.add(:picture, "should be less than 5MB")
    end
  end

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_many :posts
  has_many :comments
  
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :email, :password, :password_confirmation])
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: %i[show edit update destroy]

  # GET /comments
  # GET /comments.json
  def index
    @comment = Comment.paginate(page: params[:page], per_page: 10)
  end

  # GET /comments/1
  # GET /comments/1.json
  def show
    @comment = Comment.find_by id: params[:id]
  end

  # GET /comments/new
  def new
    @comment = Comment.new
  end

  # GET /comments/1/edit
  def edit
    @comment = Comment.find_by id: params[:id]
  end

  # POST /comments
  # POST /comments.json
  def create
    @comment = current_user.comments.build(comment_params)
    if current_user.nil?
      redirect_to new_user_session_path
    else
      respond_to do |format|
        if @comment.save
          format.html { redirect_to @comment.post, notice: 'Comment was successfully created.' }
          format.json { render :show, status: :created, location: @comment }
        else
          format.html { render :new }
          format.json { render json: @comment.errors, status: :unprocessable_entity }
        end
      end
    end
  end

  # PATCH/PUT /comments/1
  # PATCH/PUT /comments/1.json
  def update
    respond_to do |format|
      if @comment.update(comment_params)
        format.html { redirect_to @comment.post, notice: 'Comment was successfully updated.' }
        format.json { render :show, status: :ok, location: @comment }
      else
        format.html { render :edit }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comments/1
  # DELETE /comments/1.json
  def destroy
    @comment.destroy
    respond_to do |format|
      format.html { redirect_to comments_url, notice: 'Comment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_comment
    @comment = Comment.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def comment_params
    params.require(:comment).permit(:content, :post_id)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.paginate(page: params[:page], per_page: 10)
    @post = Post.find_by id: params[:id]
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
    @post = Post.find_by id: params[:id]
    if @comment.nil?
      @comment = Comment.new
    else
      @comment = Comment.find_by id: params[:id]
    end
  end

  # GET /posts/new
  def new
    @post = current_user.posts.build
  end

  # GET /posts/1/edit
  def edit
    @post = Post.find_by id: params[:id]
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = current_user.posts.build(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:title, :content, :tag_list, :picture)
    end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  before_action :authenticate_user!
  def home
  end
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  def index
    @tags = ActsAsTaggableOn::Tag.all
  end

  def show
    @tag =  ActsAsTaggableOn::Tag.find(params[:id])
    @posts = Post.tagged_with(@tag.name)
  end

  def new
    @article = Article.new
  end

  def create
  end

  def update
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/microposts_helper.rb
module MicropostsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/acts_as_taggable_on/tags/_tag.html.erb
<%= link_to tag.name, tag_path(tag) %>

app/views/comments/_form.html.erb
<%= form_with(model: comment, local: true) do |form| %>
  <% if comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>
      <% comment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :content %>
    <%= form.text_area :content, class: 'form-control'%>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/comments/edit.html.erb
<h1>Editing Comment</h1>

<%= render 'form', comment: @comment %>

<%= link_to 'Show', @comment %> |
<%= link_to 'Back', comments_path %>

app/views/comments/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Comments</h1>

<table>
  <thead>
    <tr>
      <th>Content</th>
      <th>User</th>
      <th>Post</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @comments.each do |comment| %>
      <tr>
        <td><%= comment.content %></td>
        <td><%= comment.user %></td>
        <td><%= comment.post %></td>
        <td><%= link_to 'Show', comment %></td>
        <td><%= link_to 'Edit', edit_comment_path(comment) %></td>
        <td><%= link_to 'Destroy', comment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Comment', new_comment_path %>

app/views/comments/new.html.erb
<h1>New Comment</h1>

<%= render 'form', comment: @comment %>

<%= link_to 'Back', comments_path %>

app/views/comments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Content:</strong>
  <%= @comment.content %>
</p>

<p>
  <strong>User:</strong>
  <%= @comment.user %>
</p>

<p>
  <strong>Post:</strong>
  <%= @comment.post %>
</p>

<%= link_to 'Edit', edit_comment_path(@comment) %> |
<%= link_to 'Back', comments_path %>

app/views/layouts/_flash.html.erb
<div class="container-fluid">
  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>
</div>

app/views/layouts/_footer.html.erb
<footer>
  <div class="container">
    <p>© Your Website 2018. All Rights Reserved.</p>
    <ul class="list-inline">
      <li class="list-inline-item">
        <a href="#">Privacy</a>
      </li>
      <li class="list-inline-item">
        <a href="#">Terms</a>
      </li>
      <li class="list-inline-item">
        <a href="#">FAQ</a>
      </li>
    </ul>
  </div>
</footer>

app/views/layouts/_nav.html.erb
<nav class="navbar navbar-expand-lg navbar-light fixed-top" id="mainNav">
  <div class="container">
    <a class="navbar-brand js-scroll-trigger" href="/">Home</a>
    <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
      Menu
      <i class="fas fa-bars"></i>
    </button>
    <div class="collapse navbar-collapse" id="navbarResponsive">
      <ul class="navbar-nav ml-auto">
       <% if current_user.present? %>
        <li class="nav-item">
          <%= link_to 'Read post', posts_path , class: "nav-link js-scroll-trigger" %>
        </li>

        <li class="nav-item">
          <%= link_to 'Create post', new_post_path , class: "nav-link js-scroll-trigger" %>
        </li>

        <div class="dropdown">
          <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <%= current_user.name %>
          </button>
          <div class="dropdown-menu">
            <a class="dropdown-item" href="#">Profile</a>
            <%= link_to 'Log out', destroy_user_session_path, class: 'dropdown-item', method: :delete, data: { confirm: 'Are you sure?' } %>
          </div>
        </div>
      <% else %>
        <li class="nav-item">
          <%= link_to 'Read post', posts_path , class: "nav-link js-scroll-trigger" %>
        </li>
        <li class="nav-item">
          <%= link_to 'Sign up', new_user_registration_path , class: "nav-link js-scroll-trigger" %>
        </li>
        <li class="nav-item">
          <%= link_to 'Sign in', user_session_path , class: "nav-link js-scroll-trigger" %>
        </li>
      </ul>
      <% end %>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FrontendCore</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body id="page-top">
    <%= render 'layouts/nav' %>
    <%= yield %>
  </body>
  <%= render 'layouts/footer' %>
</body>
</html>

app/views/posts/_form.html.erb
<div class='background-form'>
  <div class='row justify-content-center align-items-center h-100'>
    <div class='col col-sm-6 col-md-6 col-lg-4 col-xl-3'>
      <%= form_with(model: post, local: true) do |form| %>
      <% if post.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(post.errors.count, "error") %>
            prohibited this post from being saved:</h2>

          <ul>
            <% post.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
          </ul>
        </div>
      <% end %>

      <div class="form-group">
        <%= form.label :title%>
        <%= form.text_field :title, class: 'form-control'%>
      </div>

      <div class="form-group">
        <%= form.label :content%>
        <%= form.text_area :content, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= form.label :tag_list %>
        <%= form.text_field :tag_list, value: form.object.tag_list.to_s, class: 'form-control' %>
      </div>

      <span class="picture">
        <%= form.file_field :picture, accept: 'image/jpeg,image/gif,image/png' %>
      </span>

      <div class="actions">
        <%= form.submit 'POST', class: 'btn btn-outline-primary' %>
      </div>

    <% end %>

  </div>
</div>
</div>

app/views/posts/_post.html.erb
<h2><%= link_to post.title, post_path(post) %></h2>

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
  <center>
    <h1>Posts</h1>
  </center>
  <%= render 'layouts/flash' %>
  <% @posts.each do |post| %>
    <div class="timeline">
      <div class="container left">
        <div class="content">
          <img src="https://www.w3schools.com/bootstrap/img_avatar1.png" alt="Card image cap" style="width: 45px;">
          <strong>Title:<%= post.title %></strong>
          <h2><%= post.created_at %></h2>
          <p><%= post.content %><br></p>
          <%= image_tag post.picture.url if post.picture? %>
          <h4>Tags</h4>
          <%= render post.tags %> <br> <br>
          <%= link_to 'Read more...', post_path(post), class:'btn btn-primary' %>
          <%= link_to 'Delete', post_path(post), method: :delete, data: { confirm: 'Are you sure' }, class: 'btn btn-outline-danger' %>
          <%= link_to 'Edit', edit_post_path(post), class: 'btn btn-outline-warning' %>
        </div>
      </div>
    </div>
    <br>
  <% end %>
  <% if current_user.present? %>
    <center><%= link_to 'New Post', new_post_path, class: 'btn btn-outline-primary'%></center>
  <% else %>
    <center><%= link_to 'Sign in to create post', new_user_session_path, class: 'btn btn-outline-primary' %>
  <% end %>
</div>


<%= will_paginate @post %>

app/views/posts/new.html.erb
<%= render 'form', post: @post %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
  <br><br><br>
  <div class="timeline">
    <div class="container left">
      <div class="content">
        <img src="https://www.w3schools.com/bootstrap/img_avatar1.png" alt="Card image cap" style="width: 45px;">
        <strong>Title:<%= @post.title %></strong>
        <h2><%= @post.created_at %></h2>
        <p><%= @post.content %><br></p>
        <div><%= render @post.tags %></div>
        <%= image_tag @post.picture.url if @post.picture? %> <br> <br>
        <%= link_to 'Edit', edit_post_path(@post), class: 'btb btn-outline-primary' %>
        |
        <%= link_to 'Back', posts_path, class: 'btb btn-outline-primary' %>

        <%= form_for @comment do |form| %>
      <% else %>
        <% if @comment.errors.any? %>
          <div id="error_explanation">
            <h2><%= pluralize(comment.errors.count, "error") %>
              prohibited this comment from being saved:</h2>

            <ul>
              <% @comment.errors.full_messages.each do |message| %>
                <li><%= message %></li>
              <% end %>
            </ul>
          </div>
        <% end %>

        <div class="form-group">
          <%= form.hidden_field :post_id, :value => @post.id %>
        </div>

        <div class="form-group">
          <%= form.text_area :content, class: 'form-control'%>
        </div>

        <div class="actions">
          <%= form.submit 'Comment', class: 'btn btn-primary' %>
        </div>
      <% end %>

      <br>
      <%= @post.comments.each do |c| %>
        <div class="timeline">
          <div class="container left">
            <div class="content">
              <img src="https://www.w3schools.com/bootstrap/img_avatar1.png" alt="Card image cap" style="width: 45px;">
              <%= c.user.name %>
              <small> <i>Posted on <%= c.created_at %> </i> </small> <br>
              <%= c.content %>
              <br>
            </div>
          </div>
        </div>
      <% end %>
  </div>
</div>
</div>

app/views/static_pages/home.html.erb
<body id="page-top">
  <header class="masthead">
    <div class="container h-100">
      <div class="row h-100">
        <div class="col-lg-7 my-auto">
          <div class="header-content mx-auto">
            <%= render 'layouts/flash' %>
            <h1 class="mb-5">New Age is an app landing page that will help you beautifully showcase your new mobile app, or anything else!</h1>
            <a href="#download" class="btn btn-outline btn-xl js-scroll-trigger">Start Now for Free!</a>
          </div>
        </div>
        <div class="col-lg-5 my-auto">
          <div class="device-container">
            <div class="device-mockup iphone6_plus portrait white">
              <div class="device">
                <div class="screen">
                  <!-- Demo image for screen mockup, you can put an image here, some HTML, an animation, video, or anything else! -->
                  <img src="https://blackrockdigital.github.io/startbootstrap-new-age/img/demo-screen-1.jpg" class="img-fluid" alt="">
                </div>
                <div class="button">
                  <!-- You can hook the "home button" to some JavaScript events or just remove it -->
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </header>
</body>

app/views/tags/index.html.erb
<h1>Tags</h1>
<%= render @tags %>

app/views/tags/show.html.erb
<br><br><br>
<h1><%= @tag.name %></h1>
<div><%= render @posts %></div>